2024-07-25 01:27:15,124 - apscheduler.scheduler - INFO - Scheduler started
2024-07-25 01:27:25,769 - __main__ - ERROR - Exception while handling an update:
Traceback (most recent call last):
  File "/home/lemidb/lm/Net_Desktop/pythonProject/ChatBot/new_env/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 425, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/lemidb/lm/Net_Desktop/pythonProject/ChatBot/new_env/lib/python3.10/site-packages/telegram/ext/handler.py", line 145, in handle_update
    return self.callback(update, context)
  File "/home/lemidb/lm/Net_Desktop/pythonProject/ChatBot/portfolio/tg_portfolio.py", line 68, in my_handler
    project_details(update,context)
  File "/home/lemidb/lm/Net_Desktop/pythonProject/ChatBot/portfolio/tg_portfolio.py", line 39, in project_details
    update.message.reply_text('Select an option to learn more about the project:', reply_markup=reply_markup)
AttributeError: 'NoneType' object has no attribute 'reply_text'
2024-07-25 01:29:06,324 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-07-25 01:29:06,325 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-07-25 01:29:06,560 - telegram.ext.updater - WARNING - Exiting immediately!
2024-07-25 01:29:07,744 - apscheduler.scheduler - INFO - Scheduler started
2024-07-25 01:31:09,598 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-07-25 01:31:09,598 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-07-25 01:31:10,862 - telegram.ext.updater - WARNING - Exiting immediately!
2024-07-25 01:31:12,506 - apscheduler.scheduler - INFO - Scheduler started
2024-07-25 01:31:26,172 - __main__ - ERROR - Exception while handling an update:
Traceback (most recent call last):
  File "/home/lemidb/lm/Net_Desktop/pythonProject/ChatBot/new_env/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 425, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/lemidb/lm/Net_Desktop/pythonProject/ChatBot/new_env/lib/python3.10/site-packages/telegram/ext/handler.py", line 145, in handle_update
    return self.callback(update, context)
  File "/home/lemidb/lm/Net_Desktop/pythonProject/ChatBot/portfolio/tg_portfolio.py", line 76, in my_handler
    handle_project_detail(update,context)
  File "/home/lemidb/lm/Net_Desktop/pythonProject/ChatBot/portfolio/tg_portfolio.py", line 86, in handle_project_detail
    description=ProjectInfo[project]['description']
KeyError: 'jit_library'
2024-07-25 01:38:52,290 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-07-25 01:38:52,291 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-07-25 01:38:52,554 - telegram.ext.updater - WARNING - Exiting immediately!
2024-07-25 01:40:22,525 - apscheduler.scheduler - INFO - Scheduler started
2024-07-25 01:44:45,511 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-07-25 01:44:45,512 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-07-25 01:44:45,749 - telegram.ext.updater - WARNING - Exiting immediately!
2024-07-25 01:44:47,683 - apscheduler.scheduler - INFO - Scheduler started
2024-07-25 01:46:17,230 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-07-25 01:46:17,230 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-07-25 01:46:18,191 - telegram.ext.updater - WARNING - Exiting immediately!
2024-07-25 01:46:20,694 - apscheduler.scheduler - INFO - Scheduler started
2024-07-25 01:46:33,538 - __main__ - ERROR - Exception while handling an update:
Traceback (most recent call last):
  File "/home/lemidb/lm/Net_Desktop/pythonProject/ChatBot/new_env/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 425, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/lemidb/lm/Net_Desktop/pythonProject/ChatBot/new_env/lib/python3.10/site-packages/telegram/ext/handler.py", line 145, in handle_update
    return self.callback(update, context)
  File "/home/lemidb/lm/Net_Desktop/pythonProject/ChatBot/portfolio/tg_portfolio.py", line 82, in my_handler
    description=ProjectInfo[project]['description']
KeyError: 'jit_library'
2024-07-25 01:47:53,874 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-07-25 01:47:53,874 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-07-25 01:47:54,118 - telegram.ext.updater - WARNING - Exiting immediately!
2024-07-25 01:47:56,344 - apscheduler.scheduler - INFO - Scheduler started
2024-07-25 01:48:13,959 - __main__ - ERROR - Exception while handling an update:
Traceback (most recent call last):
  File "/home/lemidb/lm/Net_Desktop/pythonProject/ChatBot/new_env/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 425, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/lemidb/lm/Net_Desktop/pythonProject/ChatBot/new_env/lib/python3.10/site-packages/telegram/ext/handler.py", line 145, in handle_update
    return self.callback(update, context)
  File "/home/lemidb/lm/Net_Desktop/pythonProject/ChatBot/portfolio/tg_portfolio.py", line 83, in my_handler
    description=ProjectInfo[project]['description']
KeyError: 'jit_library'
2024-07-25 02:03:00,509 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x725976710760>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /bot6192945152:AAGaM_RX7F9fY2wBhcCE00zdY1bGPtgHSRw/getUpdates
2024-07-25 02:04:40,454 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-07-25 02:04:40,454 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-07-25 02:04:40,724 - telegram.ext.updater - WARNING - Exiting immediately!
2024-07-25 02:10:40,522 - apscheduler.scheduler - INFO - Scheduler started
2024-07-25 02:13:06,686 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-07-25 02:13:06,687 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-07-25 02:13:06,909 - telegram.ext.updater - WARNING - Exiting immediately!
2024-07-25 08:01:39,508 - apscheduler.scheduler - INFO - Scheduler started
2024-07-25 08:08:15,783 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-07-25 08:08:15,783 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-07-25 08:08:16,038 - telegram.ext.updater - WARNING - Exiting immediately!
2024-07-25 08:08:24,584 - apscheduler.scheduler - INFO - Scheduler started
2024-07-25 08:10:30,037 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-07-25 08:10:30,037 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-07-25 08:10:30,258 - telegram.ext.updater - WARNING - Exiting immediately!
2024-07-25 08:12:00,449 - apscheduler.scheduler - INFO - Scheduler started
2024-07-25 08:13:08,182 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-07-25 08:13:08,182 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-07-25 08:13:12,269 - telegram.ext.updater - WARNING - Exiting immediately!
2024-07-25 08:13:14,800 - apscheduler.scheduler - INFO - Scheduler started
2024-07-25 08:27:04,418 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-07-25 08:27:04,418 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-07-25 08:27:04,624 - telegram.ext.updater - WARNING - Exiting immediately!
2024-07-25 08:27:09,085 - apscheduler.scheduler - INFO - Scheduler started
2024-07-25 08:30:03,218 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-07-25 08:30:03,218 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-07-25 08:39:45,490 - apscheduler.scheduler - INFO - Scheduler started
2024-07-25 08:47:14,920 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-07-25 08:47:14,920 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-07-25 08:47:15,142 - telegram.ext.updater - WARNING - Exiting immediately!
2024-07-25 08:47:20,383 - apscheduler.scheduler - INFO - Scheduler started
2024-07-25 08:48:52,274 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-07-25 08:48:52,274 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-07-25 08:48:52,512 - telegram.ext.updater - WARNING - Exiting immediately!
2024-07-25 08:48:57,125 - apscheduler.scheduler - INFO - Scheduler started
2024-07-25 09:01:39,354 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-07-25 09:01:39,354 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-07-25 09:01:39,609 - telegram.ext.updater - WARNING - Exiting immediately!
2024-07-25 09:01:44,671 - apscheduler.scheduler - INFO - Scheduler started
2024-07-25 09:03:40,617 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-07-25 09:03:40,617 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-07-25 09:03:40,916 - telegram.ext.updater - WARNING - Exiting immediately!
2024-07-25 09:03:44,423 - apscheduler.scheduler - INFO - Scheduler started
2024-07-25 09:04:48,430 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-07-25 09:04:48,430 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-07-25 09:04:48,714 - telegram.ext.updater - WARNING - Exiting immediately!
2024-07-25 09:04:50,056 - apscheduler.scheduler - INFO - Scheduler started
2024-07-25 09:09:32,632 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-07-25 09:09:32,632 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-07-25 09:09:32,848 - telegram.ext.updater - WARNING - Exiting immediately!
2024-07-25 09:09:34,739 - apscheduler.scheduler - INFO - Scheduler started
2024-07-25 09:09:55,407 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-07-25 09:09:55,407 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-07-25 09:09:55,659 - telegram.ext.updater - WARNING - Exiting immediately!
2024-07-25 09:09:56,839 - apscheduler.scheduler - INFO - Scheduler started
2024-07-25 10:06:50,695 - __main__ - ERROR - Exception while handling an update:
Traceback (most recent call last):
  File "D:\PERSONAL\MYPC\PROJECTS\python\myenv\Lib\site-packages\telegram\ext\dispatcher.py", line 425, in process_update
    handler.handle_update(update, self, check, context)
  File "D:\PERSONAL\MYPC\PROJECTS\python\myenv\Lib\site-packages\telegram\ext\handler.py", line 145, in handle_update
    return self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PERSONAL\MYPC\PROJECTS\python\IMPORTANT\CHATBOTS\my_portfolio_bot\tg_portfolio.py", line 84, in my_handler
    handle_project_details(update,context)
  File "D:\PERSONAL\MYPC\PROJECTS\python\IMPORTANT\CHATBOTS\my_portfolio_bot\tg_portfolio.py", line 96, in handle_project_details
    project = stack.pop()
              ^^^^^^^^^^^
IndexError: pop from empty list
2024-07-25 10:06:57,505 - __main__ - ERROR - Exception while handling an update:
Traceback (most recent call last):
  File "D:\PERSONAL\MYPC\PROJECTS\python\myenv\Lib\site-packages\telegram\ext\dispatcher.py", line 425, in process_update
    handler.handle_update(update, self, check, context)
  File "D:\PERSONAL\MYPC\PROJECTS\python\myenv\Lib\site-packages\telegram\ext\handler.py", line 145, in handle_update
    return self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PERSONAL\MYPC\PROJECTS\python\IMPORTANT\CHATBOTS\my_portfolio_bot\tg_portfolio.py", line 84, in my_handler
    handle_project_details(update,context)
  File "D:\PERSONAL\MYPC\PROJECTS\python\IMPORTANT\CHATBOTS\my_portfolio_bot\tg_portfolio.py", line 96, in handle_project_details
    project = stack.pop()
              ^^^^^^^^^^^
IndexError: pop from empty list
2024-07-25 10:06:59,682 - __main__ - ERROR - Exception while handling an update:
Traceback (most recent call last):
  File "D:\PERSONAL\MYPC\PROJECTS\python\myenv\Lib\site-packages\telegram\ext\dispatcher.py", line 425, in process_update
    handler.handle_update(update, self, check, context)
  File "D:\PERSONAL\MYPC\PROJECTS\python\myenv\Lib\site-packages\telegram\ext\handler.py", line 145, in handle_update
    return self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PERSONAL\MYPC\PROJECTS\python\IMPORTANT\CHATBOTS\my_portfolio_bot\tg_portfolio.py", line 78, in my_handler
    handle_project_details(update,context)
  File "D:\PERSONAL\MYPC\PROJECTS\python\IMPORTANT\CHATBOTS\my_portfolio_bot\tg_portfolio.py", line 96, in handle_project_details
    project = stack.pop()
              ^^^^^^^^^^^
IndexError: pop from empty list
2024-07-25 10:07:01,690 - __main__ - ERROR - Exception while handling an update:
Traceback (most recent call last):
  File "D:\PERSONAL\MYPC\PROJECTS\python\myenv\Lib\site-packages\telegram\ext\dispatcher.py", line 425, in process_update
    handler.handle_update(update, self, check, context)
  File "D:\PERSONAL\MYPC\PROJECTS\python\myenv\Lib\site-packages\telegram\ext\handler.py", line 145, in handle_update
    return self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PERSONAL\MYPC\PROJECTS\python\IMPORTANT\CHATBOTS\my_portfolio_bot\tg_portfolio.py", line 82, in my_handler
    handle_project_details(update,context)
  File "D:\PERSONAL\MYPC\PROJECTS\python\IMPORTANT\CHATBOTS\my_portfolio_bot\tg_portfolio.py", line 96, in handle_project_details
    project = stack.pop()
              ^^^^^^^^^^^
IndexError: pop from empty list
2024-07-25 10:07:03,241 - __main__ - ERROR - Exception while handling an update:
Traceback (most recent call last):
  File "D:\PERSONAL\MYPC\PROJECTS\python\myenv\Lib\site-packages\telegram\ext\dispatcher.py", line 425, in process_update
    handler.handle_update(update, self, check, context)
  File "D:\PERSONAL\MYPC\PROJECTS\python\myenv\Lib\site-packages\telegram\ext\handler.py", line 145, in handle_update
    return self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PERSONAL\MYPC\PROJECTS\python\IMPORTANT\CHATBOTS\my_portfolio_bot\tg_portfolio.py", line 80, in my_handler
    handle_project_details(update,context)
  File "D:\PERSONAL\MYPC\PROJECTS\python\IMPORTANT\CHATBOTS\my_portfolio_bot\tg_portfolio.py", line 96, in handle_project_details
    project = stack.pop()
              ^^^^^^^^^^^
IndexError: pop from empty list
2024-07-25 10:07:05,136 - __main__ - ERROR - Exception while handling an update:
Traceback (most recent call last):
  File "D:\PERSONAL\MYPC\PROJECTS\python\myenv\Lib\site-packages\telegram\ext\dispatcher.py", line 425, in process_update
    handler.handle_update(update, self, check, context)
  File "D:\PERSONAL\MYPC\PROJECTS\python\myenv\Lib\site-packages\telegram\ext\handler.py", line 145, in handle_update
    return self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PERSONAL\MYPC\PROJECTS\python\IMPORTANT\CHATBOTS\my_portfolio_bot\tg_portfolio.py", line 84, in my_handler
    handle_project_details(update,context)
  File "D:\PERSONAL\MYPC\PROJECTS\python\IMPORTANT\CHATBOTS\my_portfolio_bot\tg_portfolio.py", line 96, in handle_project_details
    project = stack.pop()
              ^^^^^^^^^^^
IndexError: pop from empty list
